#include "uds_definitions.h"

SERVICE_ID_INFO SERVICE_RANGE_INFO_TABLE[] = {
    {0x00,0x0F,SI_TYPE::OBD_SERVICE_REQUESTS,SI_DEFINITION::ISO_15031_5},
    {0x10,0x3E,SI_TYPE::ISO_14229_1_SERVICE_REQUEST,SI_DEFINITION::ISO_14229_1},
    {0x3F,0x3F,SI_TYPE::NOT_APPLICABLE,SI_DEFINITION::RESERVED_BY_DOCUMENT},
    {0x40,0x4F,SI_TYPE::OBD_SERVICE_RESPONSE,SI_DEFINITION::ISO_15031_5},
    {0x50,0x7E,SI_TYPE::ISO_14229_1_POSITIVE_SERVICE_RESPONSES,SI_DEFINITION::ISO_14229_1},
    {0x7F,0x7F,SI_TYPE::NEGATIVE_RESPONSE_SERVICE_ID,SI_DEFINITION::ISO_14229_1},
    {0x80,0x80,SI_TYPE::NOT_APPLICABLE,SI_DEFINITION::RESERVED_BY_ISO_14229_1},
    {0x81,0x82,SI_TYPE::NOT_APPLICABLE,SI_DEFINITION::RESERVED_BY_ISO_14230},
    {0x83,0x88,SI_TYPE::ISO_14229_1_SERVICE_REQUEST,SI_DEFINITION::ISO_14229_1},
    {0x89,0x9F,SI_TYPE::SERVICE_REQUESTS,SI_DEFINITION::RESERVED_FOR_FUTURE_EXPANSION_AS_NEEDED},
    {0xA0,0xB9,SI_TYPE::SERVICE_REQUESTS,SI_DEFINITION::DEFINED_BY_VEHICLE_MANUFACTURER},
    {0xBA,0xBE,SI_TYPE::SERVICE_REQUESTS,SI_DEFINITION::DEFINED_BY_SYSTEM_SUPPLIER},
    {0xBF,0xBF,SI_TYPE::NOT_APPLICABLE,SI_DEFINITION::RESERVED_BY_DOCUMENT},
    {0xC0,0xC0,SI_TYPE::NOT_APPLICABLE,SI_DEFINITION::RESERVED_BY_ISO_14229_1},
    {0xC1,0xC2,SI_TYPE::NOT_APPLICABLE,SI_DEFINITION::RESERVED_BY_ISO_14230},
    {0xC3,0xC8,SI_TYPE::ISO_14229_1_POSITIVE_SERVICE_RESPONSES,SI_DEFINITION::ISO_14229_1},
    {0xC9,0xDF,SI_TYPE::POSITIVE_SERVICE_RESPONSES,SI_DEFINITION::RESERVED_FOR_FUTURE_EXPANSION_AS_NEEDED},
    {0xE0,0xF9,SI_TYPE::POSITIVE_SERVICE_RESPONSES,SI_DEFINITION::DEFINED_BY_VEHICLE_MANUFACTURER},
    {0xFA,0xFE,SI_TYPE::POSITIVE_SERVICE_RESPONSES,SI_DEFINITION::DEFINED_BY_SYSTEM_SUPPLIER},
    {0xFF,0xFF,SI_TYPE::NOT_APPLICABLE,SI_DEFINITION::RESERVED_BY_DOCUMENT},
};

UDS_DIAG_SERVICE_INFO UDS_DIAG_SERVICE_INFO_TABLE[UDS_MANAGER_SUPPORTED_SERVICE_COUNT] = {
    {UDS_DIAG_SESSION_CONTROL_REQUEST_SID           ,UDS_DIAG_SESSION_CONTROL_RESPONSE_SID          ,DIAG_SESSION_ACCESS_ALLOWED},
    {UDS_DIAG_RESET_REQUEST_SID                     ,UDS_DIAG_RESET_RESPONSE_SID                    ,DIAG_SESSION_ACCESS_ALLOWED},
    {UDS_DIAG_SEC_ACCESS_REQUEST_SID                ,UDS_DIAG_SEC_ACCESS_RESPONSE_SID               ,DIAG_SESSION_ACCESS_NA},
    {UDS_DIAG_COMMUNICATION_CONTROL_REQUEST_SID     ,UDS_DIAG_COMMUNICATION_CONTROL_RESPONSE_SID    ,DIAG_SESSION_ACCESS_NA},
    {UDS_DIAG_TESTER_PRESENT_REQUEST_SID            ,UDS_DIAG_TESTER_PRESENT_RESPONSE_SID           ,DIAG_SESSION_ACCESS_ALLOWED},
    {UDS_DIAG_ACCESS_TIMING_PARAM_REQUEST_SID       ,UDS_DIAG_ACCESS_TIMING_PARAM_RESPONSE_SID      ,DIAG_SESSION_ACCESS_NA},
    {UDS_DIAG_SECURED_DATA_TRANSMISSION_REQUEST_SID ,UDS_DIAG_SECURED_DATA_TRANSMISSION_RESPONSE_SID,DIAG_SESSION_ACCESS_NA},
    {UDS_DIAG_CONTROL_DTC_SETTINGS_REQUEST_SID      ,UDS_DIAG_CONTROL_DTC_SETTINGS_RESPONSE_SID     ,DIAG_SESSION_ACCESS_NA},
    {UDS_DIAG_RESPONSES_ON_EVENT_REQUEST_SID        ,UDS_DIAG_RESPONSES_ON_EVENT_RESPONSE_SID       ,DIAG_SESSION_ACCESS_ALLOWED},
    {UDS_DIAG_LINK_CONTROL_REQUEST_SID              ,UDS_DIAG_LINK_CONTROL_RESPONSE_SID             ,DIAG_SESSION_ACCESS_NA},
    {UDS_READ_DATA_BY_ID_REQUEST_SID                ,UDS_READ_DATA_BY_ID_RESPONSE_SID               ,DIAG_SESSION_ACCESS_ALLOWED},
    {UDS_READ_MEMORY_BY_ADDRESS_REQUEST_SID         ,UDS_READ_MEMORY_BY_ADDRESS_RESPONSE_SID        ,DIAG_SESSION_ACCESS_ALLOWED},
    {UDS_READ_SCALING_DATA_BY_ID_REQUEST_SID        ,UDS_READ_SCALING_DATA_BY_ID_RESPONSE_SID       ,DIAG_SESSION_ACCESS_ALLOWED},
    {UDS_READ_DATA_BY_ID_PERIODIC_REQUEST_SID       ,UDS_READ_DATA_BY_ID_PERIODIC_RESPONSE_SID      ,DIAG_SESSION_ACCESS_NA},
    {UDS_DINAMICALLY_DEFINE_DATA_ID_REQUEST_SID     ,UDS_DINAMICALLY_DEFINE_DATA_ID_RESPONSE_SID    ,DIAG_SESSION_ACCESS_ALLOWED},
    {UDS_WRITE_DATA_BY_ID_REQUEST_SID               ,UDS_WRITE_DATA_BY_ID_RESPONSE_SID              ,DIAG_SESSION_ACCESS_ALLOWED},
    {UDS_WRITE_MEMORY_BY_ADDRESS_REQUEST_SID        ,UDS_WRITE_MEMORY_BY_ADDRESS_RESPONSE_SID       ,DIAG_SESSION_ACCESS_ALLOWED},
    {UDS_CLEAR_DTC_REQUEST_SID                      ,UDS_CLEAR_DTC_RESPONSE_SID                     ,DIAG_SESSION_ACCESS_ALLOWED},
    {UDS_READ_DTC_REQUEST_SID                       ,UDS_READ_DTC_RESPONSE_SID                      ,DIAG_SESSION_ACCESS_ALLOWED},
    {UDS_IO_CTRL_BY_ID_REQUEST_SID                  ,UDS_IO_CTRL_BY_ID_RESPONSE_SID                 ,DIAG_SESSION_ACCESS_NA},
    {UDS_ROUTINE_CTRL_REQUEST_SID                   ,UDS_ROUTINE_CTRL_RESPONSE_SID                  ,DIAG_SESSION_ACCESS_ALLOWED},
    {UDS_REQ_DOWNLOAD_REQUEST_SID                   ,UDS_REQ_DOWNLOAD_RESPONSE_SID                  ,DIAG_SESSION_ACCESS_NA},
    {UDS_REQ_UPLOAD_REQUEST_SID                     ,UDS_REQ_UPLOAD_RESPONSE_SID                    ,DIAG_SESSION_ACCESS_NA},
    {UDS_TRANSFER_DATA_REQUEST_SID                  ,UDS_TRANSFER_DATA_RESPONSE_SID                 ,DIAG_SESSION_ACCESS_NA},
    {UDS_TRANSFER_EXIT_REQUEST_SID                  ,UDS_TRANSFER_EXIT_RESPONSE_SID                 ,DIAG_SESSION_ACCESS_NA},
};

std::string_view TranslateServiceID(uint8_t SID){
    switch(SID){
        case 0x10: return "Diagnostic Session Controll";
        case 0x11: return "ECU Reset";
        case 0x27: return "Security access";
        case 0x28: return "Communication controll";
        case 0x3E: return "Tester Present";
        case 0x83: return "Access Timing Parameter";
        case 0x84: return "Secured data transmission";
        case 0x85: return "Control DTC Setting";
        case 0x86: return "Response on Event";
        case 0x87: return "Link Control";
        case 0x22: return "Read data by IDentifier";
        case 0x23: return "Read memory by address";
        case 0x24: return "Read scalling data by IDentifier";
        case 0x2A: return "Read data by periodic IDentifier";
        case 0x2C: return "Dynamically define data IDentifier";
        case 0x2E: return "Write data by IDentifier";
        case 0x3D: return "Write data by Address";
        case 0x14: return "Clear diagnostic information";
        case 0x19: return "Read DTC information";
        case 0x2F: return "I/O Control by IDentifier";
        case 0x31: return "Routine controll";
        case 0x34: return "Request download";
        case 0x35: return "Request upload";
        case 0x36: return "Transfer data";
        case 0x37: return "Request transfer Exit";

        default: return "Unknown";
    }
}
